### ISSUE TITLE
Need logo in place of text

### ISSUE THREAD

**Issue by anyweez** [ccgriswold/sf-product-customizer#13]
Southern Flavor logo in PSD

**Comment by wheatbrad** [comment]
@anyweez  @ccgriswold  I've pushed a branch dubbed `site-logo` that takes care of this issue. however, when I click to initiate a pull request i'm transported to my repo for the sf-product-customizer. maybe if one of you guys initiate the pull request things will play smoothly?

just a rundown of my process to get to this point:
- I cloned the repo to a local directory
- created `site-logo` branch, made changes to satisfy this issue
- pushed `site-logo` branch

**Comment by ccgriswold** [comment]
If I see a pull request come through I'll approve it and try a pull request as well.

**Comment by wheatbrad** [comment]
@ccgriswold I didn't initiate a PR. I tried to, but it jumped over to my repo. I'll do some research — i'm sure there is some maneuver to do this properly. 

But, you might want to initiate the request yourself.

**Comment by anyweez** [comment]
done in https://github.com/wheatbrad/sf-product-customizer/pull/5

**Comment by anyweez** [comment]
crap false wrong way, one sec

**Comment by anyweez** [comment]
here https://github.com/ccgriswold/sf-product-customizer/pull/32

**Comment by ccgriswold** [comment]
Thank you brad. Header image successful. Closing this now
