### ISSUE TITLE
Add "Our Story" section

### ISSUE THREAD

**Issue by anyweez** [ccgriswold/sf-product-customizer#14]
background is video, along with circular headshots and bios. caleb is working on getting the mock. clay will take this afterwards.

**Comment by anyweez** [comment]
from @cam4859:

here's the link from Ryan H. dudes!
https://www.dropbox.com/sh/9qvs1uz9oaf9xgu/AACPoW07iYDMh3Si7E2AHA0ha?dl=0.
Note - the order should be: Me, Ryan, Derek, Dad, Asher (Not Me, Derek,
Ryan). How are the bios going to appear underneath the photos, when they
drag or click one of us?

**Comment by cam4859** [comment]
See screen shot of reply from Ryan below regarding bio blurbs (and disregard excessive emojis)

Best Wishes,

Caleb Musser 
President 
Musser & Company
919.624.6049
MusserandCompany.com

**Comment by anyweez** [comment]
@cam4859 you down to leave bio's out for now? i'm not sure where we can put them as-is and getting the interaction right will take some time (prob need to do some animation, get the positioning right, etc).

I'd suggest queuing this up for post-launch if possible.

**Comment by cam4859** [comment]
Would it be relatively easy to have the bios fixed/static beneath the
photos like so? Feel free to tell me to piss off if not lol.
[image: Inline image 1]

Best Regards,

Caleb Musser
President
Musser & Company
919.624.6049
MusserandCompany.com

**Comment by cam4859** [comment]
But yes, if it's too difficult to get the bio's up there, then totally fine
to leave them off for now. I would like to get them up over the next couple
days, maybe something for Brad to take on?

Best Regards,

Caleb Musser
President
Musser & Company
919.624.6049
MusserandCompany.com

**Comment by ccgriswold** [comment]
@cam4859 The picture in the mock up for this section.  I haven't come across (or haven't noticed that I've seen) this background picture. Do you know the location I can find it? Thank you

**Comment by cam4859** [comment]
I think it is a layer in the photoshop file that Ryan uploaded. Brad should
be able to pull it.

Best Regards,

Caleb Musser
President
Musser & Company
919.624.6049
MusserandCompany.com

On Tue, Oct 11, 2016 at 11:01 PM, Clayton Griswold <notifications@github.com

**Comment by cam4859** [comment]
Speaking of which, do you all have the list for Brad yet?

Best Regards,

Caleb Musser
President
Musser & Company
919.624.6049
MusserandCompany.com

**Comment by cam4859** [comment]
Since Brad is the only one with photoshop, it seems to make the most sense
to have him match Ryan's designs and manipulate the PSD file. Thoughts?

Best Regards,

Caleb Musser
President
Musser & Company
919.624.6049
MusserandCompany.com

**Comment by cam4859** [comment]
Clay - here is the link the Facebook page;
https://www.facebook.com/SouthernFavor/

Best Regards,

Caleb Musser
President
Musser & Company
919.624.6049
MusserandCompany.com

**Comment by cam4859** [comment]
Hey guys - just a thought, but try looking through the Shopify apps/plugins for the coaster crop function (and similar needs). I think Brad found one before... One of the major benefits of Shopify that we've probably over-looked is all of their off-the-shelf apps for product customization. 

Best Wishes,

Caleb Musser 
President 
Musser & Company
919.624.6049
MusserandCompany.com

**Comment by cam4859** [comment]
I'm pretty sure a lot of functions like the photo upload Clays had issues with already exist in Shopify's app store. 

Best Wishes,

Caleb Musser 
President 
Musser & Company
919.624.6049
MusserandCompany.com

**Comment by cam4859** [comment]
So yeah, I guess as you guys work through this, make sure to check Shopifys store to see if similar apps/plugins already exist (even if it's a little different but achieves the same general purpose) . That way we're not recreating the wheel and hopefully making it easier/faster for y'all.

Ok that was the last one for the night lol night gents. 

Best Wishes,

Caleb Musser 
President 
Musser & Company
919.624.6049
MusserandCompany.com

**Comment by anyweez** [comment]
@ccgriswold giving this to you since I think you're already deep into it.

**Comment by ccgriswold** [comment]
All elements added and css complete
