### ISSUE TITLE
Add real box descriptions.

### ISSUE THREAD

**Issue by anyweez** [ccgriswold/sf-product-customizer#18]
Caleb to write (add them here) then we can add.

**Comment by cam4859** [comment]
__All Message Boxes are hand-crafted with American hardwood and leather in Charlotte, NC. Each box is filled with raffia straw and contains a parchment card for a hand-written note to the gift recipient._ 

Artillery Box: 8.25" x 5.5" x 4.25" The SF Artillery Box is hand-crafted with American hardwood and leather. While it looks like it might have fallen off of a pirate's ship, it's refined and regal enough to sit on your favorite buccaneer's mantle.  
Ammo Box: 8.25" x 5.5" x 4.25" Hand-crafted with American pride and care, the SF Ammo Box is a rustic throw-back to when Davy Crockett was still King of the Wild Frontier.  
Buckshot Box: 5.75" x 5.5" x 4.25" While they may not use it to lug around buckshot, this carefully crafted, petite box is perfect for that special Southern Bell (or Buck) in your life.  
Letter Box: 5.75" x 5.5" x 1" The hand-written letter is a fading art, so we brought is back and made it 100X's more meaningful. Perfect for delivering the hand-written letter and SF coasters, the Letter Box is sure to store trinkets and treasures on dressers for years to come.

**Comment by anyweez** [comment]
Thanks! I'll take this.
