### ISSUE TITLE
Add real box dimensions

### ISSUE THREAD

**Issue by anyweez** [ccgriswold/sf-product-customizer#19]

**Comment by cam4859** [comment]
Artillery Box: 8.25" x 5.5" x 4.25" (Box 
Ammo Box: 8.25" x 5.5" x 4.25"
Buckshot Box: 5.75" x 5.5" x 4.25" 
Letter Box: 5.75" x 5.5" x 1"

**Comment by anyweez** [comment]
👍  great @cam4859, thanks! Where do these need to go? I'm not seeing them in Ryan's designs.

Look at this man using github like a champ.

**Comment by cam4859** [comment]
Lol shooting over a mockup image via email right now!

**Comment by cam4859** [comment]
​I was thinking something like the below. Thoughts? We could not show the
dimensions until they click on a particular box.
[image: Inline image 2]​

Best Regards,

Caleb Musser
President
Musser & Company
919.624.6049
MusserandCompany.com

**Comment by cam4859** [comment]
(moved by luke to https://github.com/ccgriswold/sf-product-customizer/issues/14)

**Comment by anyweez** [comment]
Dimensions look good to me! @ccgriswold I'm going to add this to the boxes objects in `boxes.js` as three separate properties: `length`, `width`, and `height`. Then we can do whatever we need to with them (including render them as Caleb has them in the mock).

I can do the actual rendering later, or you can knock it out since I think you're working on that section of the page anyway. Lemme know.

**Comment by ccgriswold** [comment]
By render do you mean adding the picture to the site? I'll take a look at the boxes.js to get a better grasp.

**Comment by anyweez** [comment]
I think the easiest way to add in dimensions is going to be to create the `#boxBox` content by looping over the boxes. Then we can pull the name, description, image, etc from there and keep all of that in one place, including dimensions.

**Comment by ccgriswold** [comment]
Gotcha.  Yea I'll try and get to that in a bit.

**Comment by anyweez** [comment]
I'm going to make a change to `boxes.js` to make this a bit easier. I wasn't thinking about that when I moved everything over and I'm afraid I limited our options a bit. brb.

**Comment by anyweez** [comment]
Not currently sure where the right place to put this is, and the old stuff got lost when we moved to product customizer. I'll look into this.

**Comment by ccgriswold** [comment]
Done and done
