### ISSUE TITLE
Dramatically decrease load time

### ISSUE THREAD

**Issue by anyweez** [ccgriswold/sf-product-customizer#22]
The page currently takes over a minute to load at my house...I need to download about 65MB of files (!!!) before the window load event occurs, which is much, much longer than most people will wait. 

Let's (a) shrink the images to smaller dimensions that fit the place they're going on the page, and (b) try to reformat the video to see if we can make it much smaller (this is the main culprit).

**Comment by ccgriswold** [comment]
Yea they are super large images and that video is like 40mb on it's own.  When I move them over to the shopify location I'll see if I can reformat to a smaller size.

**Comment by anyweez** [comment]
I have some ideas for the video -- I'll give that one a shot in a sec. I think the issues will mostly be a matter of resizing them (shouldn't have to do anything overly fancy, fingers crossed).

**Comment by ccgriswold** [comment]
Good to hear.  Also if it's causing major trouble we can table it for a short while.  I have a black background fallback incase the video never loaded.  If you comment out the video tag section it will not load the background video every time you reload the page.

**Comment by ccgriswold** [comment]
All pictures are reduced to less than 1 MB per picture. From their previous 5-15 MB. This has drastically decreased those picture load times.  The video compression I still have not successfully done.

**Comment by anyweez** [comment]
Good! I have a reduced video that's 90% smaller (3.5M instead of 37M). Gonna try to reduce it a bit more but will upload to Dropbox and comment here in a bit.

**Comment by ccgriswold** [comment]
Awesome! What program did you use? We have the kickstarter video that will be going into the "our story" section that needs to be significantly reduced as well.  It's sitting at over 215MB currently unreduced.

**Comment by anyweez** [comment]
The video is in here, called `Highlight30sec.reduced.30.mp4`:
https://www.dropbox.com/home/SF%20Website%20Design/Video%20for%20Loop. @ccgriswold can you take care of uploading to Shopify and changing the URL's in the HTML?

I used a program called ffmpeg. Happy to scale down another video if you want. Open another issue if so?

**Comment by anyweez** [comment]
FYI @cam4859 the resolution is a bit lower than the original but the page loads MUUUUUCH faster. I tested it in the background and couldn't really tell but lemme know if its too grainy and I can up the quality. Just remember that any improvements to quality means (potentially significant) increase in page load time.

**Comment by cam4859** [comment]
Hey man - where is the site living? the below link is broken. If you guys
can let me know which Shopify package I need to get, I'll go ahead and do
that.

https://cgrizzy.myshopify.com/?key=e7a6f0b76c08756638f05bafeb0d109ac9ba2f838092eee651d0cb78030f2770

Best Regards,

Caleb Musser
President
Musser & Company
919.624.6049
MusserandCompany.com

**Comment by ccgriswold** [comment]
Hey Caleb,

The past link expired because the trial ended. I have set up a new mock site but the style sheet hasn’t been imported to it.  This website: http://www.websitetooltester.com/en/reviews/shopify/pricing/ http://www.websitetooltester.com/en/reviews/shopify/pricing/ has the price breakdowns for what each level gets.  I don’t think we need anything hire than the basic but I’ll let you make the final decision after seeing the benefits of each level.

**Comment by ccgriswold** [comment]
Hey @anyweez where is the new 30sec video located? I clicked the link you attached but it redirected me to the video for loop folder with the previous uncompressed version of the video.

**Comment by cam4859** [comment]
Hey man - here is link to 30 sec loop videos:
https://www.dropbox.com/sh/a1w3wehsjb0mw3e/AABpIFd4GBI6V4LSzfypnDwua?dl=0

Best Regards,

Caleb Musser
President
Musser & Company
919.624.6049
MusserandCompany.com

On Wed, Oct 12, 2016 at 12:13 PM, Clayton Griswold <notifications@github.com

**Comment by cam4859** [comment]
(moved to slack since this is public)
