### ISSUE TITLE
Compressed Videos

### ISSUE THREAD

**Issue by ccgriswold** [ccgriswold/sf-product-customizer#27]
We need to reduce the size of the current videos in the site to improve performance.

**Comment by ccgriswold** [comment]
@anyweez  , if you have a couple spare minutes could you compress this one as well? Thank you https://www.dropbox.com/s/47l1zfqiwh5rfzb/KickstarterFinalCut.mp4?dl=0

**Comment by anyweez** [comment]
Added as `KickstarterFinalCut.reduced.mp4`. This one isn't as short so I could only get it down to 14MB. I'd suggest we don't use this as a background video if possible -- it's about as big as the rest of the site combined. We can sort that out later if needed but def not ideal.

**Comment by anyweez** [comment]
Assigning back to you @ccgriswold.

**Comment by ccgriswold** [comment]
Awesome! Thank you sir. I was planning to add it in the Our story section with a press to play button (not auto play) with a placeholder image until it loads maybe hosted from like youtube or something like that so our site doesn't have to straight download the video on each reload

**Comment by anyweez** [comment]
@ccgriswold can we finish this up on the live site?

**Comment by ccgriswold** [comment]
Actually I think we can close this issue.  There were just the two videos and thanks to your compression software they are shrunk down.
